[2025-08-10 13:59:53,233: INFO: main: We are in main]
[2025-08-13 22:13:05,923: INFO: main: We are in main]
[2025-08-13 22:33:00,106: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-13 22:33:00,106: INFO: common: yaml file: C:\Users\Shyam\OneDrive\Desktop\Kidney-disease-Classification\config\config.yaml loaded successfully]
[2025-08-13 22:33:00,106: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-13 22:33:00,106: INFO: common: created directory at: artifacts]
[2025-08-13 22:33:00,106: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-13 22:33:00,106: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts\data_ingestion\data.zip]
[2025-08-13 22:33:43,854: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts\data_ingestion\data.zip]
[2025-08-13 22:33:44,367: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-14 08:12:14,749: INFO: common: yaml file: C:\Users\Shyam\OneDrive\Desktop\Kidney-disease-Classification\config\config.yaml loaded successfully]
[2025-08-14 08:12:14,756: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-14 08:12:14,756: INFO: common: created directory at: artifacts]
[2025-08-14 08:12:14,760: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-14 08:12:49,946: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 08:12:50,096: INFO: 356742809: model saved at artifacts\prepare_base_model\base_model.h5\base_model.h5]
[2025-08-14 08:12:50,146: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 08:12:50,258: INFO: 356742809: model saved at artifacts\prepare_base_model\base_model_updated.h5\base_model.h5]
[2025-08-14 08:19:07,181: INFO: common: yaml file: C:\Users\Shyam\OneDrive\Desktop\Kidney-disease-Classification\config\config.yaml loaded successfully]
[2025-08-14 08:19:07,184: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-14 08:19:07,186: INFO: common: created directory at: artifacts]
[2025-08-14 08:19:07,187: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-14 08:19:07,405: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 08:19:07,406: INFO: 1172428320: Error occurred while preparing base model: [Errno 13] Unable to synchronously create file (unable to open file: name = 'artifacts\prepare_base_model\base_model.h5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)]
[2025-08-14 08:20:50,368: INFO: common: yaml file: C:\Users\Shyam\OneDrive\Desktop\Kidney-disease-Classification\config\config.yaml loaded successfully]
[2025-08-14 08:20:50,372: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-14 08:20:50,372: INFO: common: created directory at: artifacts]
[2025-08-14 08:20:50,374: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-14 08:20:50,573: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 08:20:50,573: INFO: 1172428320: Error occurred while preparing base model: [Errno 13] Unable to synchronously create file (unable to open file: name = 'artifacts\prepare_base_model\base_model.h5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)]
[2025-08-14 08:21:50,605: INFO: common: yaml file: C:\Users\Shyam\OneDrive\Desktop\Kidney-disease-Classification\config\config.yaml loaded successfully]
[2025-08-14 08:21:50,608: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-14 08:21:50,609: INFO: common: created directory at: artifacts]
[2025-08-14 08:21:50,610: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-14 08:21:50,827: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 08:21:50,827: INFO: 1172428320: Error occurred while preparing base model: [Errno 13] Unable to synchronously create file (unable to open file: name = 'artifacts\prepare_base_model\base_model.h5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)]
[2025-08-14 08:41:22,394: INFO: common: yaml file: C:\Users\Shyam\OneDrive\Desktop\Kidney-disease-Classification\config\config.yaml loaded successfully]
[2025-08-14 08:41:22,397: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-14 08:41:22,398: INFO: common: created directory at: artifacts]
[2025-08-14 08:41:22,399: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-14 08:41:22,602: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 08:41:22,683: INFO: 1172428320: Error occurred while preparing base model: 'Logger' object has no attribute 'INFO']
[2025-08-14 08:41:49,240: INFO: common: yaml file: C:\Users\Shyam\OneDrive\Desktop\Kidney-disease-Classification\config\config.yaml loaded successfully]
[2025-08-14 08:41:49,243: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-14 08:41:49,244: INFO: common: created directory at: artifacts]
[2025-08-14 08:41:49,246: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-14 08:41:49,447: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 08:41:49,547: INFO: 311329356: Base model saved at artifacts\prepare_base_model\base_model.h5\base_model.h5]
[2025-08-14 08:41:49,572: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 08:41:49,641: INFO: 311329356: Base model saved at artifacts\prepare_base_model\base_model_updated.h5\base_model.h5]
[2025-08-14 08:46:50,049: INFO: common: yaml file: C:\Users\Shyam\OneDrive\Desktop\Kidney-disease-Classification\config\config.yaml loaded successfully]
[2025-08-14 08:46:50,053: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-14 08:46:50,055: INFO: common: created directory at: artifacts]
[2025-08-14 08:46:50,056: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-14 08:46:50,263: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 08:46:50,385: INFO: 763838465: model saved at artifacts\prepare_base_model\base_model.h5\Base Model.h5]
[2025-08-14 08:46:50,410: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 08:46:50,521: INFO: 763838465: model saved at artifacts\prepare_base_model\base_model_updated.h5\Updated Base Model.h5]
[2025-08-14 08:47:30,167: INFO: common: yaml file: C:\Users\Shyam\OneDrive\Desktop\Kidney-disease-Classification\config\config.yaml loaded successfully]
[2025-08-14 08:47:30,172: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-14 08:47:30,173: INFO: common: created directory at: artifacts]
[2025-08-14 08:47:30,174: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-14 08:47:30,379: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 08:47:30,473: INFO: 763838465: model saved at artifacts\prepare_base_model\base_model.h5\Base Model.h5]
[2025-08-14 08:47:30,496: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 08:47:30,579: INFO: 763838465: model saved at artifacts\prepare_base_model\base_model_updated.h5\Updated Base Model.h5]
[2025-08-14 08:49:31,535: INFO: common: yaml file: C:\Users\Shyam\OneDrive\Desktop\Kidney-disease-Classification\config\config.yaml loaded successfully]
[2025-08-14 08:49:31,539: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-14 08:49:31,541: INFO: common: created directory at: artifacts]
[2025-08-14 08:49:31,542: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-14 08:49:31,755: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 08:49:31,837: INFO: 677877822: model saved at artifacts\prepare_base_model\base_model.h5\Base_Model.h5]
[2025-08-14 08:49:31,861: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 08:49:31,956: INFO: 677877822: model saved at artifacts\prepare_base_model\base_model_updated.h5\Updated_Base_Model.h5]
[2025-08-14 13:49:33,583: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-14 13:49:33,583: INFO: common: yaml file: C:\Users\Shyam\OneDrive\Desktop\Kidney-disease-Classification\config\config.yaml loaded successfully]
[2025-08-14 13:49:33,583: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-14 13:49:33,583: INFO: common: created directory at: artifacts]
[2025-08-14 13:49:33,596: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-14 13:49:33,596: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts\data_ingestion\data.zip]
[2025-08-14 13:49:58,737: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts\data_ingestion\data.zip]
[2025-08-14 13:49:59,216: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-14 13:49:59,216: INFO: main: *******************]
[2025-08-14 13:49:59,216: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-08-14 13:49:59,216: ERROR: main: name 'PrepareBaseModelTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "C:\Users\Shyam\OneDrive\Desktop\Kidney-disease-Classification\main.py", line 19, in <module>
    prepare_base_model = PrepareBaseModelTrainingPipeline()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'PrepareBaseModelTrainingPipeline' is not defined
[2025-08-14 13:51:16,496: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-14 13:51:16,496: INFO: common: yaml file: C:\Users\Shyam\OneDrive\Desktop\Kidney-disease-Classification\config\config.yaml loaded successfully]
[2025-08-14 13:51:16,498: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-14 13:51:16,499: INFO: common: created directory at: artifacts]
[2025-08-14 13:51:16,499: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-14 13:51:16,499: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts\data_ingestion\data.zip]
[2025-08-14 13:51:39,506: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts\data_ingestion\data.zip]
[2025-08-14 13:51:40,034: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-14 13:51:40,034: INFO: main: *******************]
[2025-08-14 13:51:40,034: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-08-14 13:51:40,034: INFO: common: yaml file: C:\Users\Shyam\OneDrive\Desktop\Kidney-disease-Classification\config\config.yaml loaded successfully]
[2025-08-14 13:51:40,034: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-14 13:51:40,034: INFO: common: created directory at: artifacts]
[2025-08-14 13:51:40,034: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-14 13:51:40,322: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 13:51:40,418: INFO: model_preparation: model saved at artifacts\prepare_base_model\base_model.h5\Base_Model.h5]
[2025-08-14 13:51:40,438: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-14 13:51:40,519: INFO: model_preparation: model saved at artifacts\prepare_base_model\base_model_updated.h5\Updated_Base_Model.h5]
[2025-08-14 13:51:40,519: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
